services:

  hello-node-demo-5:
    restart: always
    image: node-dockerfile-demo-1
    container_name: hello-node-demo-5
    stop_grace_period: 30s  # 优雅等待 30 秒后 再停止。即 docker-compose stop 执行后 30秒 完全停止。
    stop_signal: SIGTERM     # 发送优雅停止信号
    ports:
      - 3015:3000
  
  hello-node-demo6:
    restart: always
    image: node-dockerfile-demo-1
    container_name: hello-node-demo-6
    ports:
      - 3016:3000
  
  hello-node-demo-7:
    restart: always
    image: node-dockerfile-demo-1
    container_name: hello-node-demo-7
    ports:
      - 3017:3000
