FROM tomcat

WORKDIR /usr/local/tomcat/webapps/

RUN mkdir ROOT

RUN echo 'hello my dockerfile v2.1' > /usr/local/tomcat/webapps/ROOT/index.html

RUN echo '<h1>hello a.html</h1>' > /usr/local/tomcat/webapps/ROOT/a.html
