FROM tomcat

WORKDIR /usr/local/tomcat/webapps/

RUN mkdir ROOT

RUN echo 'hello This is My DockerFile ... demo2' > /usr/local/tomcat/webapps/ROOT/index.html

COPY 1.png /usr/local/tomcat/webapps/ROOT
